"""Add read and deletion flags to messages

Revision ID: 52661312cf61
Revises: 
Create Date: 2025-04-24 18:15:16.370837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52661312cf61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_recipient', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_recipient')
        batch_op.drop_column('deleted_by_sender')
        batch_op.drop_column('read')

    # ### end Alembic commands ###
